# Generated by Django 6.0.1 on 2026-01-26 18:07

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SourceDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_status', models.CharField(choices=[('approved', 'Approved for Publishing'), ('waiting', 'Waiting for Review'), ('adjustment', 'Needs Adjustment')], default='waiting')),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('markdown', models.TextField(blank=True, null=True)),
                ('md_version', models.URLField(blank=True, null=True)),
                ('rtf_version', models.URLField(blank=True, null=True)),
                ('title', models.CharField()),
                ('created_at', models.DateField(blank=True, null=True)),
                ('metro_doc_type', models.CharField(blank=True, choices=[('agenda', 'Agenda'), ('board_report', 'Board Report')], null=True)),
                ('doc_id', models.CharField(blank=True, null=True, unique=True)),
                ('source_url', models.URLField(help_text='Link to the original document. Since they are uploaded as pdfs, this field can serve as the pdf version.')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('content', 0), ('image', 1), ('react_block', 4)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Specify a title for this block. (Optional)', 'required': False}), 3: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Specify a description for this block. (Optional)', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('title', 2), ('description', 3)]], {})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ExampleModelDetailPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('content', 0), ('image', 1), ('react_block', 4)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Specify a title for this block. (Optional)', 'required': False}), 3: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Specify a description for this block. (Optional)', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('title', 2), ('description', 3)]], {})})),
                ('object', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='la_metro_translations.examplemodel')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='TranslatedDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_status', models.CharField(choices=[('approved', 'Approved for Publishing'), ('waiting', 'Waiting for Review'), ('adjustment', 'Needs Adjustment')], default='waiting')),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('markdown', models.TextField(blank=True, null=True)),
                ('md_version', models.URLField(blank=True, null=True)),
                ('rtf_version', models.URLField(blank=True, null=True)),
                ('language', models.CharField(choices=[('es', 'Spanish')])),
                ('pdf_version', models.URLField(blank=True, null=True)),
                ('source_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='la_metro_translations.sourcedoc')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
