# Generated by Django 5.1.2 on 2024-10-10 15:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("la_metro_translations", "0002_examplemodel_examplemodeldetailpage"),
        ("wagtailsearch", "0006_customise_indexentry"),
        ("wagtailredirects", "0001_initial"),
        ("wagtailforms", "0001_initial"),
    ]
