# Generated by Django 5.1.2 on 2024-10-11 15:35

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("la_metro_translations", "0003_create_default_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examplemodeldetailpage",
            name="body",
            field=wagtail.fields.StreamField(
                [("content", 0), ("image", 1), ("react_block", 4)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.RichTextBlock", (), {}),
                    1: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Specify a title for this block. (Optional)",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "help_text": "Specify a description for this block. (Optional)",
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 2), ("description", 3)]],
                        {},
                    ),
                },
            ),
        ),
        migrations.AlterField(
            model_name="staticpage",
            name="body",
            field=wagtail.fields.StreamField(
                [("content", 0), ("image", 1), ("react_block", 4)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.RichTextBlock", (), {}),
                    1: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Specify a title for this block. (Optional)",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "help_text": "Specify a description for this block. (Optional)",
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 2), ("description", 3)]],
                        {},
                    ),
                },
            ),
        ),
    ]
