# Generated by Django 6.0.1 on 2026-02-10 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('la_metro_translations', '0004_add_react_block'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('source_url', models.URLField(help_text='Link to the original pdf document.')),
                ('created_at', models.DateField(blank=True, help_text='Date this original document was created, as per the BoardAgendas app.', null=True)),
                ('document_type', models.CharField(blank=True, choices=[('event_document', 'EventDocument'), ('bill_document', 'BillDocument')], null=True)),
                ('document_id', models.CharField(blank=True, help_text='Primary key of this document in the BoardAgendas app.', null=True)),
                ('entity_type', models.CharField(blank=True, choices=[('event', 'Event'), ('bill', 'Bill')], null=True)),
                ('entity_id', models.CharField(blank=True, help_text='Primary key of this entity in the BoardAgendas app.', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('markdown', models.TextField()),
                ('approval_status', models.CharField(choices=[('approved', 'Approved for Publishing'), ('waiting', 'Waiting for Initial Review'), ('revision', 'Needs Revision')], default='waiting')),
                ('created_at', models.DateField(auto_now_add=True, help_text='Date this content was created in this app.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date this content was last updated in this app.')),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='la_metro_translations.document')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentContentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(choices=[('md', 'md'), ('rtf', 'rtf'), ('pdf', 'pdf')])),
                ('url', models.URLField(blank=True, null=True)),
                ('document_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='la_metro_translations.documentcontent')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('markdown', models.TextField()),
                ('language', models.CharField(choices=[('spanish', 'Spanish')])),
                ('approval_status', models.CharField(choices=[('approved', 'Approved for Publishing'), ('waiting', 'Waiting for Initial Review'), ('revision', 'Needs Revision')], default='waiting')),
                ('created_at', models.DateField(auto_now_add=True, help_text='Date this translation was created in this app.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date this translation was last updated in this app.')),
                ('document_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='la_metro_translations.documentcontent')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentTranslationFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(choices=[('md', 'md'), ('rtf', 'rtf'), ('pdf', 'pdf')])),
                ('url', models.URLField(blank=True, null=True)),
                ('document_translation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='la_metro_translations.documenttranslation')),
            ],
        ),
    ]
