# Generated by Django 6.0.1 on 2026-01-27 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('la_metro_translations', '0004_add_react_block'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_status', models.CharField(choices=[('approved', 'Approved for Publishing'), ('waiting', 'Waiting for Review'), ('adjustment', 'Needs Adjustment')], default='waiting')),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('markdown', models.TextField(blank=True, null=True)),
                ('md_version', models.URLField(blank=True, null=True)),
                ('rtf_version', models.URLField(blank=True, null=True)),
                ('title', models.CharField()),
                ('created_at', models.DateField(blank=True, null=True)),
                ('metro_doc_type', models.CharField(blank=True, choices=[('agenda', 'Agenda'), ('board_report', 'Board Report')], null=True)),
                ('doc_id', models.CharField(blank=True, null=True, unique=True)),
                ('source_url', models.URLField(help_text='Link to the original document. Since they are uploaded as pdfs, this field can serve as the pdf version.')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TranslatedDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_status', models.CharField(choices=[('approved', 'Approved for Publishing'), ('waiting', 'Waiting for Review'), ('adjustment', 'Needs Adjustment')], default='waiting')),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('markdown', models.TextField(blank=True, null=True)),
                ('md_version', models.URLField(blank=True, null=True)),
                ('rtf_version', models.URLField(blank=True, null=True)),
                ('language', models.CharField(choices=[('es', 'Spanish')])),
                ('pdf_version', models.URLField(blank=True, null=True)),
                ('source_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='la_metro_translations.sourcedoc')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
