# Generated by Django 6.0.2 on 2026-02-27 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('la_metro_translations', '0005_document_documentcontent_documenttranslation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='created_at',
            field=models.DateTimeField(help_text='Date this original document was created, as per the BoardAgendas app.'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_id',
            field=models.CharField(help_text='Primary key of this document in the BoardAgendas app.'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('event_document', 'EventDocument'), ('bill_document', 'BillDocument')]),
        ),
        migrations.AlterField(
            model_name='document',
            name='entity_id',
            field=models.CharField(help_text='Primary key of this entity in the BoardAgendas app.'),
        ),
        migrations.AlterField(
            model_name='document',
            name='entity_type',
            field=models.CharField(choices=[('event', 'Event'), ('bill', 'Bill')]),
        ),
        migrations.AlterField(
            model_name='document',
            name='updated_at',
            field=models.DateTimeField(help_text='Date this original document was updated, as per the BoardAgendas app.'),
        ),
    ]
