# Generated by Django 6.0.1 on 2026-01-26 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('la_metro_translations', '0005_sourcedoc_translateddoc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translateddoc',
            name='source_doc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='la_metro_translations.sourcedoc'),
        ),
    ]
