# Generated by Django 6.0.2 on 2026-03-26 21:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('la_metro_translations', '0005_document_documentcontent_documenttranslation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examplemodeldetailpage',
            name='object',
        ),
        migrations.RemoveField(
            model_name='examplemodeldetailpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='staticpage',
            name='page_ptr',
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['entity_type', 'title']},
        ),
        migrations.AlterModelOptions(
            name='documentcontent',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='documenttranslation',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterField(
            model_name='document',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 26, 21, 40, 58, 347644), help_text='Date this original document was created, as per the BoardAgendas app.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='document_id',
            field=models.CharField(default=1, help_text='Primary key of this document in the BoardAgendas app.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('event_document', 'EventDocument'), ('bill_document', 'BillDocument')]),
        ),
        migrations.AlterField(
            model_name='document',
            name='entity_id',
            field=models.CharField(help_text='Primary key of this entity in the BoardAgendas app.'),
        ),
        migrations.AlterField(
            model_name='document',
            name='entity_type',
            field=models.CharField(choices=[('event', 'Event'), ('bill', 'Bill')]),
        ),
        migrations.AlterField(
            model_name='document',
            name='updated_at',
            field=models.DateTimeField(help_text='Date this original document was updated, as per the BoardAgendas app.'),
        ),
        migrations.DeleteModel(
            name='ExampleModel',
        ),
        migrations.DeleteModel(
            name='ExampleModelDetailPage',
        ),
        migrations.DeleteModel(
            name='StaticPage',
        ),
    ]
