# Generated by Django 6.0.2 on 2026-03-26 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('la_metro_translations', '0006_remove_examplemodeldetailpage_object_and_more'),
        ('la_metro_translations', '0008_alter_document_document_type'),
    ]

    operations = [
    ]
