# Generated by Django 6.0.3 on 2026-03-27 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('la_metro_translations', '0009_merge_20260326_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('event_document', 'EventDocument'), ('bill_document', 'BillDocument'), ('bill_version', 'BillVersion')]),
        ),
    ]
