# Generated by Django 6.0.3 on 2026-03-27 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('la_metro_translations', '0010_alter_document_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Date this original document was created, as per the BoardAgendas app.'),
        ),
        migrations.AlterField(
            model_name='document',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Date this original document was updated, as per the BoardAgendas app.'),
        ),
    ]
