# Generated by Django 6.0.3 on 2026-04-03 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('la_metro_translations', '0009_remove_translationfile_url_translationfile_file_and_more'),
        ('la_metro_translations', '0011_alter_document_created_at_alter_document_updated_at'),
    ]

    operations = [
    ]
