# Generated by Django 6.0.3 on 2026-04-03 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('la_metro_translations', '0011_alter_document_created_at_alter_document_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='entity_slug',
            field=models.CharField(default='placeholder-slug', help_text='Slug to view this entity on the BoardAgendas app'),
            preserve_default=False,
        ),
    ]
