# Generated by Django 6.0.3 on 2026-04-07 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('la_metro_translations', '0012_merge_20260403_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='entity_slug',
            field=models.CharField(default='placeholder-slug', help_text='Slug to view this entity on the BoardAgendas app'),
            preserve_default=False,
        ),
    ]
