# Generated by Django 6.0.3 on 2026-04-07 17:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('la_metro_translations', '0013_document_entity_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='translationfile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 4, 7, 17, 45, 43, 506461), help_text='Date this object was created in this app.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='translationfile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Date this object was last updated in this app.'),
        ),
    ]
