# Generated by Django 6.0.3 on 2026-04-30 21:10

import wagtailmarkdown.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('la_metro_translations', '0014_translationfile_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentcontent',
            name='markdown',
            field=wagtailmarkdown.fields.MarkdownField(),
        ),
        migrations.AlterField(
            model_name='documenttranslation',
            name='markdown',
            field=wagtailmarkdown.fields.MarkdownField(),
        ),
    ]
