# Generated by Django 6.0.4 on 2026-05-12 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('la_metro_translations', '0014_translationfile_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(unique=True)),
                ('display_name', models.CharField(unique=True)),
                ('auto_approval_enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='documenttranslation',
            name='temp_lang',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translations', to='la_metro_translations.translationlanguage'),
        ),
    ]
