# Generated by Django 6.0.4 on 2026-05-15 21:10

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('la_metro_translations', '0015_alter_documentcontent_markdown_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_approve_extractions', models.BooleanField(default=True, help_text='Automatically approve extracted document content for translation. Content marked as Needs Revision will not be auto-approved.')),
            ],
            options={
                'verbose_name': 'Extraction Configuration',
            },
        ),
        migrations.CreateModel(
            name='TranslationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('language', models.CharField(choices=[('sp', 'Spanish')])),
                ('auto_approve_translations', models.BooleanField(default=True, help_text='Automatically approve machine translations in this language. Translations marked as Needs Revision will not be auto-approved.')),
                ('config', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_configs', to='la_metro_translations.extractionconfig')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
                'unique_together': {('config', 'language')},
            },
        ),
    ]
