# Generated by Django 6.0.4 on 2026-05-08 20:11

from django.db import migrations
from django.db.models import F


def languages_to_model(apps, schema_editor):
    """
    Forward function for populating new TranslationLanguage model and relating
    those new language objects to existing DocumentTranslations
    """
    DocumentTranslation = apps.get_model('la_metro_translations', 'DocumentTranslation')
    TranslationLanguage = apps.get_model('la_metro_translations', 'TranslationLanguage')
    language_choices = DocumentTranslation.language.field.choices

    # Create new TranslationLanguage objects
    translation_languages = []
    for value, display_name in language_choices:
       translation_languages.append(TranslationLanguage(value=value, display_name=display_name))

    new_language_objects = TranslationLanguage.objects.bulk_create(
        translation_languages
    )

    # Update existing DocumentTranslations with new language objects
    for lang in new_language_objects:
        docs = DocumentTranslation.objects.filter(language=lang.value)
        docs.update(temp_lang=lang)


def clear_languages_model(apps, schema_editor):
    """
    Backwards function
    """
    DocumentTranslation = apps.get_model('la_metro_translations', 'DocumentTranslation')
    DocumentTranslation.objects.all().update(language=F("temp_lang__value"))

    TranslationLanguage = apps.get_model('la_metro_translations', 'TranslationLanguage')
    TranslationLanguage.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('la_metro_translations', '0015_translationlanguage_documenttranslation_temp_lang'),
    ]

    operations = [
        migrations.RunPython(languages_to_model, clear_languages_model)
    ]
