# Generated by Django 6.0.5 on 2026-05-12 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('la_metro_translations', '0016_auto_20260508_2011'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='documenttranslation',
            name='unique_translation',
        ),
        migrations.AddConstraint(
            model_name='documenttranslation',
            constraint=models.UniqueConstraint(fields=('document_content', 'temp_lang'), name='unique_translation'),
        ),
        migrations.RemoveField(
            model_name='documenttranslation',
            name='language',
        ),
    ]
