# Generated by Django 6.0.5 on 2026-06-02 16:44

from django.db import migrations, models


def adjust_language_codes_forward(apps, schema_editor):
    """Change existing English and Spanish codes to ISO 639-3"""
    DocumentTranslation = apps.get_model("la_metro_translations.DocumentTranslation")

    english = DocumentTranslation.objects.filter(language="en")
    english.update(language="eng")

    spanish = DocumentTranslation.objects.filter(language="sp")
    spanish.update(language="spa")


def adjust_language_codes_reverse(apps, schema_editor):
    """Revert English and Spanish codes to their old forms"""
    DocumentTranslation = apps.get_model("la_metro_translations.DocumentTranslation")

    english = DocumentTranslation.objects.filter(language="eng")
    english.update(language="en")

    spanish = DocumentTranslation.objects.filter(language="spa")
    spanish.update(language="sp")


class Migration(migrations.Migration):

    dependencies = [
        ('la_metro_translations', '0016_add_extraction_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttranslation',
            name='language',
            field=models.CharField(choices=[('hye', 'Armenian (Eastern)'), ('hyw', 'Armenian (Western)'), ('zho-cn', 'Chinese (Simplified)'), ('zho-tw', 'Chinese (Traditional)'), ('eng', 'English'), ('jpn', 'Japanese'), ('kor', 'Korean'), ('rus', 'Russian'), ('spa', 'Spanish'), ('vie', 'Vietnamese')]),
        ),
        migrations.AlterField(
            model_name='translationconfig',
            name='language',
            field=models.CharField(choices=[('hye', 'Armenian (Eastern)'), ('hyw', 'Armenian (Western)'), ('zho-cn', 'Chinese (Simplified)'), ('zho-tw', 'Chinese (Traditional)'), ('jpn', 'Japanese'), ('kor', 'Korean'), ('rus', 'Russian'), ('spa', 'Spanish'), ('vie', 'Vietnamese')]),
        ),
        migrations.RunPython(
            adjust_language_codes_forward, adjust_language_codes_reverse
        ),
    ]
