# Generated by Django 6.0.5 on 2026-05-15 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('la_metro_translations', '0017_remove_documenttranslation_unique_translation_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='documenttranslation',
            name='unique_translation',
        ),
        migrations.RenameField(
            model_name='documenttranslation',
            old_name='temp_lang',
            new_name='language',
        ),
        migrations.AddConstraint(
            model_name='documenttranslation',
            constraint=models.UniqueConstraint(fields=('document_content', 'language'), name='unique_translation'),
        ),
    ]
