# Generated by Django 6.0.6 on 2026-06-10 14:08

import la_metro_translations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('la_metro_translations', '0017_alter_documenttranslation_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translationfile',
            name='file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=la_metro_translations.models.translation_file_path),
        ),
    ]
