# Generated by Django 6.0.5 on 2026-05-15 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('la_metro_translations', '0018_remove_documenttranslation_unique_translation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttranslation',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='la_metro_translations.translationlanguage'),
        ),
    ]
