# Generated by Django 6.0.6 on 2026-06-22 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('la_metro_translations', '0018_alter_translationfile_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disclaimer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('hye', 'Armenian (Eastern)'), ('hyw', 'Armenian (Western)'), ('zho-cn', 'Chinese (Simplified)'), ('zho-tw', 'Chinese (Traditional)'), ('eng', 'English'), ('jpn', 'Japanese'), ('kor', 'Korean'), ('rus', 'Russian'), ('spa', 'Spanish'), ('vie', 'Vietnamese')])),
                ('disclaimer_text', models.TextField()),
            ],
        ),
    ]
