# Generated by Django 6.0.6 on 2026-06-23 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('la_metro_translations', '0019_disclaimer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disclaimer',
            options={'ordering': ['language']},
        ),
    ]
