# Generated by Django 6.0.6 on 2026-06-26 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('la_metro_translations', '0020_alter_disclaimer_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='created_at',
            field=models.DateTimeField(help_text='Date this original document was created, as per the BoardAgendas app.'),
        ),
        migrations.AlterField(
            model_name='document',
            name='updated_at',
            field=models.DateTimeField(help_text='Date this original document was updated, as per the BoardAgendas app.'),
        ),
    ]
