# Generated by Django 6.0.6 on 2026-07-02 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('la_metro_translations', '0021_alter_document_created_at_alter_document_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disclaimer',
            name='language',
            field=models.CharField(choices=[('hye', 'Armenian (Eastern)'), ('hyw', 'Armenian (Western)'), ('zho-cn', 'Chinese (Simplified)'), ('zho-tw', 'Chinese (Traditional)'), ('eng', 'English (Accessibility)'), ('jpn', 'Japanese'), ('kor', 'Korean'), ('rus', 'Russian'), ('spa', 'Spanish'), ('vie', 'Vietnamese')]),
        ),
        migrations.AlterField(
            model_name='documenttranslation',
            name='language',
            field=models.CharField(choices=[('hye', 'Armenian (Eastern)'), ('hyw', 'Armenian (Western)'), ('zho-cn', 'Chinese (Simplified)'), ('zho-tw', 'Chinese (Traditional)'), ('eng', 'English (Accessibility)'), ('jpn', 'Japanese'), ('kor', 'Korean'), ('rus', 'Russian'), ('spa', 'Spanish'), ('vie', 'Vietnamese')]),
        ),
    ]
