# Generated by Django 6.0.7 on 2026-07-16 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('la_metro_translations', '0022_alter_disclaimer_language_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('hye', 'Armenian (Eastern)'), ('hyw', 'Armenian (Western)'), ('zho-cn', 'Chinese (Simplified)'), ('zho-tw', 'Chinese (Traditional)'), ('eng', 'English (Accessibility)'), ('jpn', 'Japanese'), ('kor', 'Korean'), ('rus', 'Russian'), ('spa', 'Spanish'), ('vie', 'Vietnamese')])),
                ('agenda_download_text', models.TextField()),
                ('board_report_download_text', models.TextField()),
            ],
            options={
                'ordering': ['language'],
            },
        ),
    ]
