# Generated by Django 6.0.7 on 2026-07-17 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('la_metro_translations', '0023_linktext'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linktext',
            options={'ordering': ['language'], 'verbose_name_plural': 'Download Link Translations'},
        ),
    ]
