# Generated by Django 6.0.6 on 2026-09-23 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('la_metro_translations', '0024_alter_linktext_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linktext',
            name='language',
            field=models.CharField(choices=[('hye', 'Armenian (Eastern)'), ('hyw', 'Armenian (Western)'), ('zho-cn', 'Chinese (Simplified)'), ('zho-tw', 'Chinese (Traditional)'), ('eng', 'English (Accessibility)'), ('jpn', 'Japanese'), ('kor', 'Korean'), ('rus', 'Russian'), ('spa', 'Spanish'), ('vie', 'Vietnamese')], unique=True),
        ),
    ]
