project:
  type: website

website:
  title: "LA Metro Translation Suite Documentation"
  sidebar:
    style: "docked"
    search: true
    contents: auto
    tools:
      - icon: github
        menu:
          - text: Source Code
            href: https://github.com/datamade/la-metro-translations
          - text: Issue Tracker
            href: https://github.com/datamade/la-metro-translations/issues

format:
  html:
    theme: litera
    css: styles.css
    toc: true
